// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package override

import (
	"github.com/sharpvik/sqlc-testdata/pkg"
)

type Bar struct {
	Other       string
	Total       int64
	AlsoRetyped pkg.CustomType
}

type Baz struct {
	Other       string
	Total       int64
	AlsoRetyped pkg.CustomType
}

type Foo struct {
	Other   string
	Total   int64
	Retyped pkg.CustomType
}
